# Test pipeline

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildENV
    displayName: "Build Enivornment (Ubuntu)"
    jobs:
      - job: CoreConfig
        displayName: "Configuring the system to core dump"
        steps:
         # - bash: "eval $(ulimit -Sc unlimited)"
            #displayName: "Setting ulimit -c"
          - bash: ". utils/setup.sh"
            name: printvar
            displayName: "Setting up core dumps"
          - bash: "ulimit -Sa"
            displayName: "Displaying set soft limits"
          - bash: "echo $(BUILD_ROOT)"
            displayName: "Build root"
          - bash: "sudo sysctl -a | grep kernel.core_pattern"
            displayName: "Displaying kernel pattern"

  - stage: BuildUbuntu
    dependsOn: BuildENV
    displayName: "Building then testing the build"
    jobs:
      - job: signalsBuild
        displayName: "iSegfault build"
        steps:
          - bash: "./isegfault/build.sh"
            displayName: "Building"

  - stage:
    dependsOn: BuildUbuntu
    displayName: "Run Tests"
    jobs:
      - job:
        displayName: "Failing, utterly"
        steps:
          - bash: "./tests/isegfault-test.sh"
            displayName: "Segmentation fault test"
