# Test pipeline

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildENV
    displayName: "Build Enivornment (Ubuntu)"
    jobs:
      - job: CoreConfig
        displayName: "Configuring the system to core dump"
        steps:
          - bash: "./utils/setup.sh . $(Build.BinariesDirectory)"
            name: printvar
            displayName: "Setting up system-wide environment"
          - bash: "sudo sysctl -a | grep kernel.core_pattern"
            displayName: "Displaying kernel pattern"

  - stage: BuildUbuntu
    dependsOn: BuildENV
    displayName: "Building then testing the build"
    jobs:
      - job: signalsBuild
        displayName: "iSegfault build"
        steps:
          - bash: "./isegfault/build.sh . $(Build.BinariesDirectory)"
            displayName: "Building"
          - bash: "ls -la $(Build.BinariesDirectory)"
            displayName: "Dump of build bin folder"
          - bash: "./tests/isegfault-test.sh $(Build.BinariesDirectory)"
            displayName: "Segmentation fault test"
          - bash: "ls -l /tmp/core"
            displayName: "Contents of /tmp/core"
