# Test pipeline

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildENV
    displayName: "Build Enivornment (Ubuntu)"
    jobs:
      - job: CoreConfig
        displayName: "Configuring the system to core dump"
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: ". signals/setup.sh"
            displayName: 'Setting up core dumps'

  - stage: BuildUbuntu
    displayName: "Building Ubtuntu"
    jobs:
      - job: signalsBuild
        displayName: "iSegfault build"
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: "$BUILD_SOURCE/build.sh"
            displayName: "Building"
