# Test pipeline

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildENV
    displayName: "Build Enivornment (Ubuntu)"
    jobs:
      - job: CoreConfig
        displayName: "Configuring the system to core dump"
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: ". signals/setup.sh"
            name: printvar
            displayName: 'Setting up core dumps'
          - bash: |
              echo "BUILD_SOURCE: $(BUILD_SOURCE)"

  - stage: BuildUbuntu
    dependsOn: BuildENV
    displayName: "Building Ubtuntu"
    variables:
      BUILD_SOURCE: $[ stageDependencies.BuildENV.CoreConfig.outputs['printvar.BUILD_SOURCE'] ]
    jobs:
      - job: signalsBuild
        displayName: "iSegfault build"
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: $(BUILD_SOURCE)/build.sh
            displayName: "Building"
