# Test pipeline

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildAndTest
    displayName: "Build Enivornment (Ubuntu)"
    jobs:
      - job: CoreConfig
        displayName: "Configuring the system to core dump"
        steps:
          - bash: "$(Build.SourcesDirectory)/utils/setup.sh . $(Build.BinariesDirectory)"
            name: printvar
            displayName: "Setting up system-wide environment"
          - bash: "$(Build.SourcesDirectory)/isegfault/build.sh . $(Build.BinariesDirectory)"
            displayName: "Building"
          - bash: "$(Build.SourcesDirectory)/ithrowuncaughtex/build.sh . $(Build.BinariesDirectory)"
            displayName: "Building"
          - bash: "ls -la $(Build.BinariesDirectory)"
            displayName: "Dump of build bin folder"
          - bash: "echo $(Build.BinariesDirectory) > utils/exec_paths.txt"
            displayName: "Writing the exec path file"
          - bash: "$(Build.SourcesDirectory)/tests/isegfault-test.sh $(Build.BinariesDirectory)"
            displayName: "Segmentation fault test"
          - bash: "$(Build.SourcesDirectory)/tests/ithrowuncaughtex-test.sh $(Build.BinariesDirectory)"
            displayName: "Uncaught exception test"
          - task: PythonScript@0
            displayName: 'Run error handler test'
            inputs:
              scriptSource: 'filePath'
              scriptPath: ./utils/core-handler.py
              arguments: >- 
                test 
                /tmp/core 
                utils/exec_paths.txt
