# Test pipeline

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildENV
    displayName: "Build Enivornment (Ubuntu)"
    jobs:
      - job: CoreConfig
        displayName: "Configuring the system to core dump"
        pool:
          vmImage: 'ubtunu-latest'
        steps:
          - script: "eval $(cat signals/build.sh)"
            displayName: 'Setting up core dumps'

  - stage: Build(Ubuntu)
    displayName: "Building Ubtuntu"
    jobs:
      - job: signalsBuild
        displayName: "iSegfault build"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - bash: ./signals/build.sh
            displayName: "Building"
