# Test pipeline

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildAndTest
    displayName: "Build Enivornment (Ubuntu)"
    jobs:
      - job: CoreConfig
        displayName: "Configuring the system to core dump"
        variables:
          - name: CORE_EXEC_PATH_FILE
            value: "$(Build.StagingDirectory)/core_handler_exec_paths.txt"
          - name: CORE_DEST
            value: /tmp/core
        steps:
          - bash: "$(Build.SourcesDirectory)/script/CaptureCritical/setup.sh $(Build.SourcesDirectory) $(CORE_DEST)"
            displayName: "Setting up system-wide environment"
          - bash: "$(Build.SourcesDirectory)/isegfault/build.sh $(Build.SourcesDirectory) $(Build.BinariesDirectory)"
            displayName: "Building failure exec(1)"
          - bash: "$(Build.SourcesDirectory)/ithrowuncaughtex/build.sh $(Build.SourcesDirectory) $(Build.BinariesDirectory)"
            displayName: "Building failure exec(2)"
          - bash: "ls -la $(Build.BinariesDirectory)"
            displayName: "Dump of build bin folder"
          - bash: "echo $(Build.BinariesDirectory) > $(CORE_EXEC_PATH_FILE)"
            displayName: "Writing the exec path file"
          - bash: "$(Build.SourcesDirectory)/tests/isegfault-test.sh $(Build.BinariesDirectory)"
            displayName: "Segmentation fault test"
          - bash: "$(Build.SourcesDirectory)/tests/ithrowuncaughtex-test.sh $(Build.BinariesDirectory)"
            displayName: "Uncaught exception test"
          ################################
          # Run Linter against code base #
          ################################
          - displayName: Lint Code Base
            uses: github/super-linter@v4
            env:
              VALIDATE_ALL_CODEBASE: false
              # Change to 'master' if your main branch differs
              DEFAULT_BRANCH: main
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  - stage: Testy
    displayName: "A test to see if what's built can be used within a separate stage"
    jobs:
      - job: ReRun
        displayName: "Re-run core handler"
        variables:
          - name: CORE_EXEC_PATH_FILE
            value: "$(Build.StagingDirectory)/core_handler_exec_paths.txt"
        steps:
          - bash: "echo $(Build.BinariesDirectory) > $(CORE_EXEC_PATH_FILE)"
            displayName: "Writing the exec path file"
          - template: templates/CaptureCriticalPrepare.yml
            parameters:
              CoreDest: /tmp/core
              ArtifactTargetFolder: "$(Build.ArtifactStagingDirectory)/core"
          - bash: $(Build.SourcesDirectory)/ithrowuncaughtex/build.sh . $(Build.BinariesDirectory)
            displayName: "Building failure exec(2)"
          - task: PythonScript@0
            displayName: "Running Python Script"
            inputs:
              scriptSource: 'inline'
              script: |
                import subprocess
                from subprocess import Popen, PIPE, STDOUT, DEVNULL
                cmd = [". $(Build.SourcesDirectory)/script/CaptureCritical/env.sh; $(Build.SourcesDirectory)/tests/ithrowuncaughtex-test.sh $(Build.BinariesDirectory)"]
                proc = Popen(cmd, shell=True, stderr=subprocess.STDOUT)
          - template: templates/CaptureCriticalRun.yml
